### ISSUE TITLE
Raw value for enum case is not unique

### ISSUE THREAD

**Issue by Inaki-Bonorino-Gotelli** [cuappdev/pollo-ios#285]
I keep on having this issue in the folder secrets under the file keys.generated.swift 
// Generated using Sourcery 0.15.0 — https://github.com/krzysztofzablocki/Sourcery
// DO NOT EDIT

enum Keys: String {
    case apiURL = "1"
    case apiDevURL = "1"
    case fabricAPIKey = "1"

    var value: String {
	return self.rawValue
    }    
    static var hostURL: Keys {
        #if DEV_SERVER
        return Keys.apiDevURL
        #else
        return Keys.apiURL
        #endif
    }  
}

how can I fix this?

**Comment by drewsdunne** [comment]
You’ll need to spawn a pollo server instance and use Sourcery to enter the server addresses for a dev and production server. Our server code is also open source on here and should have detailed instructions on how to start an instance.

**Comment by Inaki-Bonorino-Gotelli** [comment]
Hey thanks for the explanation but I feel like a retard but I don't know how to do that yet can you help me out?

**Comment by Inaki-Bonorino-Gotelli** [comment]
Hi I'm sorry but how do I do all of this?

**Comment by kevinchan159** [comment]
What you first want to do is create an `env-vars.sh` file in the root directory of the project. The format of the file should be
```
export API_URL=FILL_IN
export API_DEV_URL=FILL_IN
export FABRIC_API_KEY=FILL_IN
FABRIC_BUILD_SECRET=FILL_IN
```

The `pollo-ios` codebase retrieves all of its data from a backend service `pollo-backend` (https://github.com/cuappdev/pollo-backend). We have an actual server running our backend but since you will probably just be developing locally, you will just want to follow the steps in the `pollo-backend` repo to setup the backend server locally on your computer. For the values in `env-vars.sh` you can put arbitrary values for `API_URL, FABRIC_API_KEY, & FABRIC_BUILD_SECRET`. The `API_DEV_URL` should be the url of the backend server that you are running locally (probably will be `localhost`). 

Unfortunately we don't have the resources to guide you through every step of the way but if you get stuck I would look up guides on running a backend server locally and connecting your iOS app to it.

**Comment by Inaki-Bonorino-Gotelli** [comment]
Thank you!!
