### ISSUE TITLE
Deleting last non-live question doesn't return to PollsDateView

### ISSUE THREAD

**Issue by chalo2000** [cuappdev/pollo-ios#371]
![ezgif com-resize (3)](https://user-images.githubusercontent.com/21962778/75128395-e296c600-5691-11ea-8dec-2ef9f78ac79c.gif)

Observe how the no polls message is also off-center

**Comment by jackthmp** [comment]
I think this is intentional, although I'm not sure why it goes back if the question is deleted while live vs. ended. For example if you're in class you'd want to always be in CardController waiting for new questions even if they all were deleted, otherwise you'd have to tap back into the Date from PollsDate. Also, this case only looks weird when there was only 1 poll ever for this group, so both PollsDate and CardController are empty.
The offset is due to the collectionView having a left contentOffset for the regular cells and the empty cell is just added to the CV when empty. We can mess around and maybe shift the message over or something
